apiVersion: v1
kind: Service
metadata:
  name: {{ include "accelbench.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "accelbench.labels" . | nindent 4 }}
    {{- include "accelbench.api.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "accelbench.api.selectorLabels" . | nindent 4 }}
