{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "accelbench.api.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "accelbench.labels" . | nindent 4 }}
    {{- include "accelbench.api.selectorLabels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
