{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accelbench.dbSecretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "accelbench.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "accelbench.databaseURL" . | quote }}
{{- end }}
---
{{- if and .Values.huggingface.token (not .Values.huggingface.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accelbench.hfSecretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "accelbench.labels" . | nindent 4 }}
type: Opaque
stringData:
  HF_TOKEN: {{ .Values.huggingface.token | quote }}
{{- end }}
