apiVersion: v1
kind: Service
metadata:
  name: {{ include "accelbench.fullname" . }}-web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "accelbench.labels" . | nindent 4 }}
    {{- include "accelbench.web.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "accelbench.web.selectorLabels" . | nindent 4 }}
